development:
  adapter: postgresql
  encoding: unicode
  database: ex-libris-api_development
  pool: 5
  username: ex-libris-api
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: ex-libris-api_test
  pool: 5
  username: ex-libris-api
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ex-libris-api_production
  pool: 5
  username: ex-libris-api
  password:

cucumber:
  <<: *test